### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Zoezo111**
> hello

### CODE REVIEW

**Comment by karenSh1** [comment]
Trying

**Comment by Zoezo111** [comment]
Thanks

**Comment by karenSh1** [comment]
[._20201217-Novel Coronavirus_Landscape_COVID-19.xlsx](https://github.com/karenSh1/karenSh1/files/6697498/default._20201217-Novel.Coronavirus_Landscape_COVID-19.xlsx)

**Review by Zoezo111 — COMMENTED** [review]
20210110_034020000_iOS

**Pull request closed without merging**
